name: Docker Build and Push

on: [ "workflow_dispatch", "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Docker Build
      run: docker build -t docker_image:latest .

    - name: Tagging docker image
      run: |
        
        docker tag docker_image:latest sophie1300/docker-git:${{ github.run_number }} 
        docker tag docker_image:latest sophie1300/docker-git:latest

    - name: Docker login
      uses: docker/login-action@v3.0.0
      with: 
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        
    - name: Docker push
      run: |
      
        docker push sophie1300/docker-git:${{ github.run_number }} 
        docker push sophie1300/docker-git:latest

      
    
      


    
  
